### ISSUE TITLE
大佬好像依赖有冲突

### ISSUE THREAD

**Issue by zpzy816** [chao325/QmaoTai#8]
The conflict is caused by:
    pyppeteer 0.2.4 depends on pyee<9.0.0 and >=8.1.0
    pyppeteer2 0.2.2 depends on pyee<8.0.0 and >=7.0.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by LuoJianMin730** [comment]
我也遇到这问题，有解决方式吗

**Comment by shuodagen** [comment]
大佬 timer.py 怎么解决的求支招

**Comment by shuodagen** [comment]
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    jd_seckill = JdSeckill()
  File "/home/roo/QmaoTai-master/jd_seckill/jd_spider_requests.py", line 385, in __init__
    self.timers = Timer()
  File "/home/roo/QmaoTai-master/jd_seckill/timer.py", line 24, in __init__
    self.diff_time = self.local_jd_time_diff()
  File "/home/roo/QmaoTai-master/jd_seckill/timer.py", line 48, in local_jd_time_diff
    return self.local_time() - self.jd_time()
  File "/home/roo/QmaoTai-master/jd_seckill/timer.py", line 33, in jd_time
    js = json.loads(ret)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
大佬们请教下原作者的time.py接口无法返回js数据 后续你们是怎么获取到数据的？我的能力只能做到这里了，求教。

**Comment by jianboliangcha** [comment]
![image](https://github.com/chao325/QmaoTai/assets/76782107/3170c203-c3b2-4bfc-b4d5-57c3ff140d37)
一直卡在这里
